[book]
authors = ["jason_yao"]
language = "zh"
multilingual = false
src = "src"
title = "Jason's Notes"

[build]
create-missing = false

[output.html]
default-theme = "rust"
no-section-label = true
git-repository-url = "https://github.com/shihyu/jason_note"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.search]
enable = true
limit-results = 15
teaser-word-count = 10
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = false
heading-split-level = 4
index-limit-mb = 100

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
line-numbers = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.mermaid]
copy-js = true
